[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
[project]
name = "nmr_utils"
version = "0.1.0"
description = "Custom NMR utils using ASE and Soprano"
dependencies = [
    "numpy",
    "ase>=3.29",
    "soprano==0.11.1"
]
[project.scripts]
nmr_utils = "nmr_utils.cli:main"